using System.Xml.Linq;
using UnityEngine;

public class RampConfiguration<T> : ContentConfiguration<T> where T : IContent, new()
{
    //big look up table
    static readonly byte[] rampblut =
    // generated by blutmaker.py
    {
        1 ,  2 ,  8 ,  2 ,  4 , 12 ,  4 , 12 ,  9 ,  2 , 21 ,  2 ,  4 , 12 ,  4 , 12 ,
        5 , 16 ,  5 , 16 , 13 , 13 , 13 , 12 ,  5 , 16 ,  5 , 16 , 13 , 13 , 13 , 16 ,
        7 ,  2 , 14 ,  2 ,  4 , 12 ,  4 , 12 , 20 , 26 , 25 , 26 ,  4 , 12 ,  4 , 12 ,
        5 , 16 ,  5 , 16 , 13 , 16 , 13 , 16 ,  5 , 16 ,  5 , 16 , 13 , 16 , 13 , 16 ,
        3 , 10 ,  3 , 10 , 17 , 12 , 17 , 12 ,  3 , 10 , 26 , 10 , 17 , 17 , 17 , 17 ,
        11 , 10 , 11 , 16 , 11 , 26 , 17 , 12 , 11 , 16 , 11 , 16 , 13 , 13 , 17 , 16 ,
        3 , 10 ,  3 , 10 , 17 , 17 , 17 , 17 ,  3 , 10 , 26 , 10 , 17 , 17 , 17 , 17 ,
        11 , 11 , 11 , 16 , 11 , 11 , 17 , 14 , 11 , 16 , 11 , 16 , 17 , 17 , 17 , 13 ,
        6 ,  2 , 19 ,  2 ,  4 , 12 ,  4 , 12 , 15 ,  2 , 24 ,  2 ,  4 , 12 ,  4 , 12 ,
        5 , 16 , 26 , 16 , 13 , 16 , 13 , 16 ,  5 , 16 , 26 , 16 , 13 , 16 , 13 , 16 ,
        18 ,  2 , 22 ,  2 , 26 , 12 , 26 , 12 , 23 , 26 , 26 , 26 , 26 , 12 , 26 , 12 ,
        5 , 16 , 26 , 16 , 13 , 16 , 13 , 16 ,  5 , 16 , 26 , 16 , 13 , 16 , 13 , 16 ,
        3 , 10 ,  3 , 10 , 17 , 10 , 17 , 17 ,  3 , 10 , 26 , 10 , 17 , 17 , 17 , 17 ,
        11 , 10 , 11 , 16 , 17 , 10 , 17 , 17 , 11 , 16 , 11 , 16 , 17 , 15 , 17 , 12 ,
        3 , 10 ,  3 , 10 , 17 , 17 , 17 , 17 ,  3 , 10 , 26 , 10 , 17 , 17 , 17 , 17 ,
        11 , 16 , 11 , 16 , 17 , 16 , 17 , 10 , 11 , 16 , 11 , 16 , 17 , 11 , 17 , 26
    };
    static int CalculateRampType(MapDataStore.Tile tile)
    {
        int ramplookup = 0;
        if (tile.north != null &&
            tile.north.Value.up != null &&
            tile.north.Value.isWall &&
            tile.north.Value.up.Value.isFloor)
        {
            ramplookup ^= 1;
        }
        if (tile.north != null &&
            tile.north.Value.east != null &&
            tile.north.Value.east.Value.up != null &&
            tile.north.Value.east.Value.isWall &&
            tile.north.Value.east.Value.up.Value.isFloor)
        {
            ramplookup ^= 2;
        }
        if (tile.east != null &&
            tile.east.Value.up != null &&
            tile.east.Value.isWall &&
            tile.east.Value.up.Value.isFloor)
        {
            ramplookup ^= 4;
        }
        if (tile.south != null &&
            tile.south.Value.east != null &&
            tile.south.Value.east.Value.up != null &&
            tile.south.Value.east.Value.isWall &&
            tile.south.Value.east.Value.up.Value.isFloor)
        {
            ramplookup ^= 8;
        }
        if (tile.south != null &&
            tile.south.Value.up != null &&
            tile.south.Value.isWall &&
            tile.south.Value.up.Value.isFloor)
        {
            ramplookup ^= 16;
        }
        if (tile.south != null &&
            tile.south.Value.west != null &&
            tile.south.Value.west.Value.up != null &&
            tile.south.Value.west.Value.isWall &&
            tile.south.Value.west.Value.up.Value.isFloor)
        {
            ramplookup ^= 32;
        }
        if (tile.west != null &&
            tile.west.Value.up != null &&
            tile.west.Value.isWall &&
            tile.west.Value.up.Value.isFloor)
        {
            ramplookup ^= 64;
        }
        if (tile.north != null &&
            tile.north.Value.west != null &&
            tile.north.Value.west.Value.up != null &&
            tile.north.Value.west.Value.isWall &&
            tile.north.Value.west.Value.up.Value.isFloor)
        {
            ramplookup ^= 128;
        }
        // creation should ensure in range
        if (ramplookup > 0)
        {
            return rampblut[ramplookup];
        }

        if (tile.north != null &&
            tile.north.Value.isWall)
        {
            ramplookup ^= 1;
        }
        if (tile.north != null &&
            tile.north.Value.east != null &&
            tile.north.Value.east.Value.isWall)
        {
            ramplookup ^= 2;
        }
        if (tile.east != null &&
            tile.east.Value.isWall)
        {
            ramplookup ^= 4;
        }
        if (tile.south != null &&
            tile.south.Value.east != null &&
            tile.south.Value.east.Value.isWall)
        {
            ramplookup ^= 8;
        }
        if (tile.south != null &&
            tile.south.Value.isWall)
        {
            ramplookup ^= 16;
        }
        if (tile.south != null &&
            tile.south.Value.west != null &&
            tile.south.Value.west.Value.isWall)
        {
            ramplookup ^= 32;
        }
        if (tile.west != null &&
            tile.west.Value.isWall)
        {
            ramplookup ^= 64;
        }
        if (tile.north != null &&
            tile.north.Value.west != null &&
            tile.north.Value.west.Value.isWall)
        {
            ramplookup ^= 128;
        }
        return rampblut[ramplookup];
    }
    Content[] rampList = new Content[26];
    public override bool GetValue(MapDataStore.Tile tile, MeshLayer layer, out T value)
    {
        if (tile.shape != RemoteFortressReader.TiletypeShape.RAMP)
        {
            value = default(T);
            return false;
        }
        int index = CalculateRampType(tile)-1;
        if(rampList[index] == null)
        {
            value = default(T);
            return false;
        }
        value = rampList[index].GetValue(tile, layer);
        return true;
    }

    protected override void ParseElementConditions(XElement elemtype, ContentConfiguration<T>.Content content)
    {
        var elemRamps = elemtype.Elements("ramp");
        foreach (XElement elemRamp in elemRamps)
        {
            XAttribute indexAttr = elemRamp.Attribute("index");
            if (indexAttr == null)
                continue;
            int index = 0;
            if (!int.TryParse(indexAttr.Value, out index))
                continue;
            if (index > 26)
                continue;
            rampList[index - 1] = content;
        }
    }

}
