//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_buggy_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Vector2 Steering;
        
        public Valve.VR.SteamVR_Action_Single Throttle;
        
        public Valve.VR.SteamVR_Action_Boolean Brake;
        
        public Valve.VR.SteamVR_Action_Boolean Reset;
    }
}
