//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AdventureControl.proto
// Note: requires additional types generated from: RemoteFortressReader.proto
namespace AdventureControl
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveCommandParams")]
  public partial class MoveCommandParams : global::ProtoBuf.IExtensible
  {
    public MoveCommandParams() {}
    
    [UnityEngine.SerializeField]
    private RemoteFortressReader.Coord _direction = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public RemoteFortressReader.Coord direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}