//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RemoteFortressReader.proto
namespace RemoteFortressReader
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Tiletype")]
  public partial class Tiletype : global::ProtoBuf.IExtensible
  {
    public Tiletype() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _caption = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"caption", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string caption
    {
      get { return _caption; }
      set { _caption = value; }
    }
    private RemoteFortressReader.TiletypeShape _shape = RemoteFortressReader.TiletypeShape.NO_SHAPE;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"shape", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(RemoteFortressReader.TiletypeShape.NO_SHAPE)]
    public RemoteFortressReader.TiletypeShape shape
    {
      get { return _shape; }
      set { _shape = value; }
    }
    private RemoteFortressReader.TiletypeSpecial _special = RemoteFortressReader.TiletypeSpecial.NO_SPECIAL;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"special", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(RemoteFortressReader.TiletypeSpecial.NO_SPECIAL)]
    public RemoteFortressReader.TiletypeSpecial special
    {
      get { return _special; }
      set { _special = value; }
    }
    private RemoteFortressReader.TiletypeMaterial _material = RemoteFortressReader.TiletypeMaterial.NO_MATERIAL;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"material", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(RemoteFortressReader.TiletypeMaterial.NO_MATERIAL)]
    public RemoteFortressReader.TiletypeMaterial material
    {
      get { return _material; }
      set { _material = value; }
    }
    private RemoteFortressReader.TiletypeVariant _variant = RemoteFortressReader.TiletypeVariant.NO_VARIANT;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"variant", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(RemoteFortressReader.TiletypeVariant.NO_VARIANT)]
    public RemoteFortressReader.TiletypeVariant variant
    {
      get { return _variant; }
      set { _variant = value; }
    }
    private string _direction = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TiletypeList")]
  public partial class TiletypeList : global::ProtoBuf.IExtensible
  {
    public TiletypeList() {}
    
    private readonly global::System.Collections.Generic.List<RemoteFortressReader.Tiletype> _tiletype_list = new global::System.Collections.Generic.List<RemoteFortressReader.Tiletype>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tiletype_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RemoteFortressReader.Tiletype> tiletype_list
    {
      get { return _tiletype_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapBlock")]
  public partial class MapBlock : global::ProtoBuf.IExtensible
  {
    public MapBlock() {}
    
    private int _map_x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"map_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int map_x
    {
      get { return _map_x; }
      set { _map_x = value; }
    }
    private int _map_y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"map_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int map_y
    {
      get { return _map_y; }
      set { _map_y = value; }
    }
    private int _map_z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"map_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int map_z
    {
      get { return _map_z; }
      set { _map_z = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _tiles = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"tiles", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> tiles
    {
      get { return _tiles; }
    }
  
    private readonly global::System.Collections.Generic.List<RemoteFortressReader.MatPair> _materials = new global::System.Collections.Generic.List<RemoteFortressReader.MatPair>();
    [global::ProtoBuf.ProtoMember(5, Name=@"materials", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RemoteFortressReader.MatPair> materials
    {
      get { return _materials; }
    }
  
    private readonly global::System.Collections.Generic.List<RemoteFortressReader.MatPair> _layer_materials = new global::System.Collections.Generic.List<RemoteFortressReader.MatPair>();
    [global::ProtoBuf.ProtoMember(6, Name=@"layer_materials", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RemoteFortressReader.MatPair> layer_materials
    {
      get { return _layer_materials; }
    }
  
    private readonly global::System.Collections.Generic.List<RemoteFortressReader.MatPair> _vein_materials = new global::System.Collections.Generic.List<RemoteFortressReader.MatPair>();
    [global::ProtoBuf.ProtoMember(7, Name=@"vein_materials", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RemoteFortressReader.MatPair> vein_materials
    {
      get { return _vein_materials; }
    }
  
    private readonly global::System.Collections.Generic.List<RemoteFortressReader.MatPair> _base_materials = new global::System.Collections.Generic.List<RemoteFortressReader.MatPair>();
    [global::ProtoBuf.ProtoMember(8, Name=@"base_materials", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RemoteFortressReader.MatPair> base_materials
    {
      get { return _base_materials; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _magma = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"magma", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> magma
    {
      get { return _magma; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _water = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"water", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> water
    {
      get { return _water; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _hidden = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(11, Name=@"hidden", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> hidden
    {
      get { return _hidden; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _light = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(12, Name=@"light", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> light
    {
      get { return _light; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _subterranean = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(13, Name=@"subterranean", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> subterranean
    {
      get { return _subterranean; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _outside = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(14, Name=@"outside", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> outside
    {
      get { return _outside; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _aquifer = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(15, Name=@"aquifer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> aquifer
    {
      get { return _aquifer; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _water_stagnant = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(16, Name=@"water_stagnant", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> water_stagnant
    {
      get { return _water_stagnant; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _water_salt = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(17, Name=@"water_salt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> water_salt
    {
      get { return _water_salt; }
    }
  
    private readonly global::System.Collections.Generic.List<RemoteFortressReader.MatPair> _construction_items = new global::System.Collections.Generic.List<RemoteFortressReader.MatPair>();
    [global::ProtoBuf.ProtoMember(18, Name=@"construction_items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RemoteFortressReader.MatPair> construction_items
    {
      get { return _construction_items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatPair")]
  public partial class MatPair : global::ProtoBuf.IExtensible
  {
    public MatPair() {}
    
    private int _mat_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mat_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mat_type
    {
      get { return _mat_type; }
      set { _mat_type = value; }
    }
    private int _mat_index;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mat_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mat_index
    {
      get { return _mat_index; }
      set { _mat_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ColorDefinition")]
  public partial class ColorDefinition : global::ProtoBuf.IExtensible
  {
    public ColorDefinition() {}
    
    private int _red;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"red", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int red
    {
      get { return _red; }
      set { _red = value; }
    }
    private int _green;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"green", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int green
    {
      get { return _green; }
      set { _green = value; }
    }
    private int _blue;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"blue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int blue
    {
      get { return _blue; }
      set { _blue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MaterialDefinition")]
  public partial class MaterialDefinition : global::ProtoBuf.IExtensible
  {
    public MaterialDefinition() {}
    
    private RemoteFortressReader.MatPair _mat_pair;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mat_pair", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public RemoteFortressReader.MatPair mat_pair
    {
      get { return _mat_pair; }
      set { _mat_pair = value; }
    }
    private string _id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private RemoteFortressReader.ColorDefinition _state_color = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"state_color", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public RemoteFortressReader.ColorDefinition state_color
    {
      get { return _state_color; }
      set { _state_color = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildingType")]
  public partial class BuildingType : global::ProtoBuf.IExtensible
  {
    public BuildingType() {}
    
    private int _building_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"building_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int building_type
    {
      get { return _building_type; }
      set { _building_type = value; }
    }
    private int _building_subtype;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"building_subtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int building_subtype
    {
      get { return _building_subtype; }
      set { _building_subtype = value; }
    }
    private int _building_custom;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"building_custom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int building_custom
    {
      get { return _building_custom; }
      set { _building_custom = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildingDefinition")]
  public partial class BuildingDefinition : global::ProtoBuf.IExtensible
  {
    public BuildingDefinition() {}
    
    private RemoteFortressReader.BuildingType _building_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"building_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public RemoteFortressReader.BuildingType building_type
    {
      get { return _building_type; }
      set { _building_type = value; }
    }
    private string _id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildingList")]
  public partial class BuildingList : global::ProtoBuf.IExtensible
  {
    public BuildingList() {}
    
    private readonly global::System.Collections.Generic.List<RemoteFortressReader.BuildingDefinition> _building_list = new global::System.Collections.Generic.List<RemoteFortressReader.BuildingDefinition>();
    [global::ProtoBuf.ProtoMember(1, Name=@"building_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RemoteFortressReader.BuildingDefinition> building_list
    {
      get { return _building_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MaterialList")]
  public partial class MaterialList : global::ProtoBuf.IExtensible
  {
    public MaterialList() {}
    
    private readonly global::System.Collections.Generic.List<RemoteFortressReader.MaterialDefinition> _material_list = new global::System.Collections.Generic.List<RemoteFortressReader.MaterialDefinition>();
    [global::ProtoBuf.ProtoMember(1, Name=@"material_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RemoteFortressReader.MaterialDefinition> material_list
    {
      get { return _material_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitDefinition")]
  public partial class UnitDefinition : global::ProtoBuf.IExtensible
  {
    public UnitDefinition() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _isValid = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isValid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isValid
    {
      get { return _isValid; }
      set { _isValid = value; }
    }
    private int _pos_x = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private int _pos_y = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private int _pos_z = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private RemoteFortressReader.MatPair _race = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"race", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public RemoteFortressReader.MatPair race
    {
      get { return _race; }
      set { _race = value; }
    }
    private RemoteFortressReader.ColorDefinition _profession_color = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"profession_color", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public RemoteFortressReader.ColorDefinition profession_color
    {
      get { return _profession_color; }
      set { _profession_color = value; }
    }
    private uint _flags1 = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"flags1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint flags1
    {
      get { return _flags1; }
      set { _flags1 = value; }
    }
    private uint _flags2 = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"flags2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint flags2
    {
      get { return _flags2; }
      set { _flags2 = value; }
    }
    private uint _flags3 = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"flags3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint flags3
    {
      get { return _flags3; }
      set { _flags3 = value; }
    }
    private bool _is_soldier = default(bool);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"is_soldier", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_soldier
    {
      get { return _is_soldier; }
      set { _is_soldier = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitList")]
  public partial class UnitList : global::ProtoBuf.IExtensible
  {
    public UnitList() {}
    
    private readonly global::System.Collections.Generic.List<RemoteFortressReader.UnitDefinition> _creature_list = new global::System.Collections.Generic.List<RemoteFortressReader.UnitDefinition>();
    [global::ProtoBuf.ProtoMember(1, Name=@"creature_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RemoteFortressReader.UnitDefinition> creature_list
    {
      get { return _creature_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlockRequest")]
  public partial class BlockRequest : global::ProtoBuf.IExtensible
  {
    public BlockRequest() {}
    
    private int _blocks_needed = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"blocks_needed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int blocks_needed
    {
      get { return _blocks_needed; }
      set { _blocks_needed = value; }
    }
    private int _min_x = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"min_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int min_x
    {
      get { return _min_x; }
      set { _min_x = value; }
    }
    private int _max_x = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"max_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int max_x
    {
      get { return _max_x; }
      set { _max_x = value; }
    }
    private int _min_y = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"min_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int min_y
    {
      get { return _min_y; }
      set { _min_y = value; }
    }
    private int _max_y = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"max_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int max_y
    {
      get { return _max_y; }
      set { _max_y = value; }
    }
    private int _min_z = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"min_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int min_z
    {
      get { return _min_z; }
      set { _min_z = value; }
    }
    private int _max_z = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"max_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int max_z
    {
      get { return _max_z; }
      set { _max_z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlockList")]
  public partial class BlockList : global::ProtoBuf.IExtensible
  {
    public BlockList() {}
    
    private readonly global::System.Collections.Generic.List<RemoteFortressReader.MapBlock> _map_blocks = new global::System.Collections.Generic.List<RemoteFortressReader.MapBlock>();
    [global::ProtoBuf.ProtoMember(1, Name=@"map_blocks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RemoteFortressReader.MapBlock> map_blocks
    {
      get { return _map_blocks; }
    }
  
    private int _map_x = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"map_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int map_x
    {
      get { return _map_x; }
      set { _map_x = value; }
    }
    private int _map_y = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"map_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int map_y
    {
      get { return _map_y; }
      set { _map_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlantDef")]
  public partial class PlantDef : global::ProtoBuf.IExtensible
  {
    public PlantDef() {}
    
    private int _pos_x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private int _pos_y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private int _pos_z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private int _index;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlantList")]
  public partial class PlantList : global::ProtoBuf.IExtensible
  {
    public PlantList() {}
    
    private readonly global::System.Collections.Generic.List<RemoteFortressReader.PlantDef> _plant_list = new global::System.Collections.Generic.List<RemoteFortressReader.PlantDef>();
    [global::ProtoBuf.ProtoMember(1, Name=@"plant_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RemoteFortressReader.PlantDef> plant_list
    {
      get { return _plant_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ViewInfo")]
  public partial class ViewInfo : global::ProtoBuf.IExtensible
  {
    public ViewInfo() {}
    
    private int _view_pos_x = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"view_pos_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int view_pos_x
    {
      get { return _view_pos_x; }
      set { _view_pos_x = value; }
    }
    private int _view_pos_y = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"view_pos_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int view_pos_y
    {
      get { return _view_pos_y; }
      set { _view_pos_y = value; }
    }
    private int _view_pos_z = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"view_pos_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int view_pos_z
    {
      get { return _view_pos_z; }
      set { _view_pos_z = value; }
    }
    private int _view_size_x = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"view_size_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int view_size_x
    {
      get { return _view_size_x; }
      set { _view_size_x = value; }
    }
    private int _view_size_y = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"view_size_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int view_size_y
    {
      get { return _view_size_y; }
      set { _view_size_y = value; }
    }
    private int _cursor_pos_x = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"cursor_pos_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cursor_pos_x
    {
      get { return _cursor_pos_x; }
      set { _cursor_pos_x = value; }
    }
    private int _cursor_pos_y = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"cursor_pos_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cursor_pos_y
    {
      get { return _cursor_pos_y; }
      set { _cursor_pos_y = value; }
    }
    private int _cursor_pos_z = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"cursor_pos_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cursor_pos_z
    {
      get { return _cursor_pos_z; }
      set { _cursor_pos_z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapInfo")]
  public partial class MapInfo : global::ProtoBuf.IExtensible
  {
    public MapInfo() {}
    
    private int _block_size_x = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"block_size_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int block_size_x
    {
      get { return _block_size_x; }
      set { _block_size_x = value; }
    }
    private int _block_size_y = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"block_size_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int block_size_y
    {
      get { return _block_size_y; }
      set { _block_size_y = value; }
    }
    private int _block_size_z = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"block_size_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int block_size_z
    {
      get { return _block_size_z; }
      set { _block_size_z = value; }
    }
    private int _block_pos_x = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"block_pos_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int block_pos_x
    {
      get { return _block_pos_x; }
      set { _block_pos_x = value; }
    }
    private int _block_pos_y = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"block_pos_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int block_pos_y
    {
      get { return _block_pos_y; }
      set { _block_pos_y = value; }
    }
    private int _block_pos_z = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"block_pos_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int block_pos_z
    {
      get { return _block_pos_z; }
      set { _block_pos_z = value; }
    }
    private string _world_name = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"world_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string world_name
    {
      get { return _world_name; }
      set { _world_name = value; }
    }
    private string _world_name_english = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"world_name_english", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string world_name_english
    {
      get { return _world_name_english; }
      set { _world_name_english = value; }
    }
    private string _save_name = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"save_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string save_name
    {
      get { return _save_name; }
      set { _save_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Cloud")]
  public partial class Cloud : global::ProtoBuf.IExtensible
  {
    public Cloud() {}
    
    private RemoteFortressReader.FrontType _front = RemoteFortressReader.FrontType.FRONT_NONE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"front", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(RemoteFortressReader.FrontType.FRONT_NONE)]
    public RemoteFortressReader.FrontType front
    {
      get { return _front; }
      set { _front = value; }
    }
    private RemoteFortressReader.CumulusType _cumulus = RemoteFortressReader.CumulusType.CUMULUS_NONE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cumulus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(RemoteFortressReader.CumulusType.CUMULUS_NONE)]
    public RemoteFortressReader.CumulusType cumulus
    {
      get { return _cumulus; }
      set { _cumulus = value; }
    }
    private bool _cirrus = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cirrus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool cirrus
    {
      get { return _cirrus; }
      set { _cirrus = value; }
    }
    private RemoteFortressReader.StratusType _stratus = RemoteFortressReader.StratusType.STRATUS_NONE;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"stratus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(RemoteFortressReader.StratusType.STRATUS_NONE)]
    public RemoteFortressReader.StratusType stratus
    {
      get { return _stratus; }
      set { _stratus = value; }
    }
    private RemoteFortressReader.FogType _fog = RemoteFortressReader.FogType.FOG_NONE;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fog", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(RemoteFortressReader.FogType.FOG_NONE)]
    public RemoteFortressReader.FogType fog
    {
      get { return _fog; }
      set { _fog = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorldMap")]
  public partial class WorldMap : global::ProtoBuf.IExtensible
  {
    public WorldMap() {}
    
    private int _world_width;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"world_width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int world_width
    {
      get { return _world_width; }
      set { _world_width = value; }
    }
    private int _world_height;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"world_height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int world_height
    {
      get { return _world_height; }
      set { _world_height = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _name_english = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name_english", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name_english
    {
      get { return _name_english; }
      set { _name_english = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _elevation = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"elevation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> elevation
    {
      get { return _elevation; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _rainfall = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"rainfall", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> rainfall
    {
      get { return _rainfall; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _vegetation = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"vegetation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> vegetation
    {
      get { return _vegetation; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _temperature = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"temperature", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> temperature
    {
      get { return _temperature; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _evilness = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"evilness", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> evilness
    {
      get { return _evilness; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _drainage = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"drainage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> drainage
    {
      get { return _drainage; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _volcanism = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"volcanism", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> volcanism
    {
      get { return _volcanism; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _savagery = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"savagery", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> savagery
    {
      get { return _savagery; }
    }
  
    private readonly global::System.Collections.Generic.List<RemoteFortressReader.Cloud> _clouds = new global::System.Collections.Generic.List<RemoteFortressReader.Cloud>();
    [global::ProtoBuf.ProtoMember(13, Name=@"clouds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RemoteFortressReader.Cloud> clouds
    {
      get { return _clouds; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _salinity = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(14, Name=@"salinity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> salinity
    {
      get { return _salinity; }
    }
  
    private int _map_x = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"map_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int map_x
    {
      get { return _map_x; }
      set { _map_x = value; }
    }
    private int _map_y = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"map_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int map_y
    {
      get { return _map_y; }
      set { _map_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegionMaps")]
  public partial class RegionMaps : global::ProtoBuf.IExtensible
  {
    public RegionMaps() {}
    
    private readonly global::System.Collections.Generic.List<RemoteFortressReader.WorldMap> _world_maps = new global::System.Collections.Generic.List<RemoteFortressReader.WorldMap>();
    [global::ProtoBuf.ProtoMember(1, Name=@"world_maps", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RemoteFortressReader.WorldMap> world_maps
    {
      get { return _world_maps; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CasteRaw")]
  public partial class CasteRaw : global::ProtoBuf.IExtensible
  {
    public CasteRaw() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private string _caste_id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"caste_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string caste_id
    {
      get { return _caste_id; }
      set { _caste_id = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _caste_name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"caste_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> caste_name
    {
      get { return _caste_name; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _baby_name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"baby_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> baby_name
    {
      get { return _baby_name; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _child_name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(5, Name=@"child_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> child_name
    {
      get { return _child_name; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreatureRaw")]
  public partial class CreatureRaw : global::ProtoBuf.IExtensible
  {
    public CreatureRaw() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private string _creature_id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"creature_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string creature_id
    {
      get { return _creature_id; }
      set { _creature_id = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> name
    {
      get { return _name; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _general_baby_name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"general_baby_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> general_baby_name
    {
      get { return _general_baby_name; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _general_child_name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(5, Name=@"general_child_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> general_child_name
    {
      get { return _general_child_name; }
    }
  
    private int _creature_tile = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"creature_tile", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int creature_tile
    {
      get { return _creature_tile; }
      set { _creature_tile = value; }
    }
    private int _creature_soldier_tile = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"creature_soldier_tile", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int creature_soldier_tile
    {
      get { return _creature_soldier_tile; }
      set { _creature_soldier_tile = value; }
    }
    private RemoteFortressReader.ColorDefinition _color = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public RemoteFortressReader.ColorDefinition color
    {
      get { return _color; }
      set { _color = value; }
    }
    private int _adultsize = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"adultsize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int adultsize
    {
      get { return _adultsize; }
      set { _adultsize = value; }
    }
    private readonly global::System.Collections.Generic.List<RemoteFortressReader.CasteRaw> _caste = new global::System.Collections.Generic.List<RemoteFortressReader.CasteRaw>();
    [global::ProtoBuf.ProtoMember(10, Name=@"caste", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RemoteFortressReader.CasteRaw> caste
    {
      get { return _caste; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreatureRawList")]
  public partial class CreatureRawList : global::ProtoBuf.IExtensible
  {
    public CreatureRawList() {}
    
    private readonly global::System.Collections.Generic.List<RemoteFortressReader.CreatureRaw> _creature_raws = new global::System.Collections.Generic.List<RemoteFortressReader.CreatureRaw>();
    [global::ProtoBuf.ProtoMember(1, Name=@"creature_raws", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RemoteFortressReader.CreatureRaw> creature_raws
    {
      get { return _creature_raws; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TiletypeShape")]
    public enum TiletypeShape
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_SHAPE", Value=-1)]
      NO_SHAPE = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EMPTY", Value=0)]
      EMPTY = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLOOR", Value=1)]
      FLOOR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOULDER", Value=2)]
      BOULDER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PEBBLES", Value=3)]
      PEBBLES = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WALL", Value=4)]
      WALL = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORTIFICATION", Value=5)]
      FORTIFICATION = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STAIR_UP", Value=6)]
      STAIR_UP = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STAIR_DOWN", Value=7)]
      STAIR_DOWN = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STAIR_UPDOWN", Value=8)]
      STAIR_UPDOWN = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RAMP", Value=9)]
      RAMP = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RAMP_TOP", Value=10)]
      RAMP_TOP = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BROOK_BED", Value=11)]
      BROOK_BED = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BROOK_TOP", Value=12)]
      BROOK_TOP = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TREE_SHAPE", Value=13)]
      TREE_SHAPE = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SAPLING", Value=14)]
      SAPLING = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHRUB", Value=15)]
      SHRUB = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENDLESS_PIT", Value=16)]
      ENDLESS_PIT = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BRANCH", Value=17)]
      BRANCH = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRUNK_BRANCH", Value=18)]
      TRUNK_BRANCH = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TWIG", Value=19)]
      TWIG = 19
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TiletypeSpecial")]
    public enum TiletypeSpecial
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_SPECIAL", Value=-1)]
      NO_SPECIAL = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NORMAL", Value=0)]
      NORMAL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RIVER_SOURCE", Value=1)]
      RIVER_SOURCE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WATERFALL", Value=2)]
      WATERFALL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMOOTH", Value=3)]
      SMOOTH = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FURROWED", Value=4)]
      FURROWED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WET", Value=5)]
      WET = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEAD", Value=6)]
      DEAD = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WORN_1", Value=7)]
      WORN_1 = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WORN_2", Value=8)]
      WORN_2 = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WORN_3", Value=9)]
      WORN_3 = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRACK", Value=10)]
      TRACK = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMOOTH_DEAD", Value=11)]
      SMOOTH_DEAD = 11
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TiletypeMaterial")]
    public enum TiletypeMaterial
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_MATERIAL", Value=-1)]
      NO_MATERIAL = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AIR", Value=0)]
      AIR = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOIL", Value=1)]
      SOIL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STONE", Value=2)]
      STONE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FEATURE", Value=3)]
      FEATURE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LAVA_STONE", Value=4)]
      LAVA_STONE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MINERAL", Value=5)]
      MINERAL = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FROZEN_LIQUID", Value=6)]
      FROZEN_LIQUID = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONSTRUCTION", Value=7)]
      CONSTRUCTION = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GRASS_LIGHT", Value=8)]
      GRASS_LIGHT = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GRASS_DARK", Value=9)]
      GRASS_DARK = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GRASS_DRY", Value=10)]
      GRASS_DRY = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GRASS_DEAD", Value=11)]
      GRASS_DEAD = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLANT", Value=12)]
      PLANT = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HFS", Value=13)]
      HFS = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAMPFIRE", Value=14)]
      CAMPFIRE = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIRE", Value=15)]
      FIRE = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ASHES", Value=16)]
      ASHES = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAGMA", Value=17)]
      MAGMA = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DRIFTWOOD", Value=18)]
      DRIFTWOOD = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"POOL", Value=19)]
      POOL = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BROOK", Value=20)]
      BROOK = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RIVER", Value=21)]
      RIVER = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROOT", Value=22)]
      ROOT = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TREE_MATERIAL", Value=23)]
      TREE_MATERIAL = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MUSHROOM", Value=24)]
      MUSHROOM = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNDERWORLD_GATE", Value=25)]
      UNDERWORLD_GATE = 25
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TiletypeVariant")]
    public enum TiletypeVariant
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_VARIANT", Value=-1)]
      NO_VARIANT = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VAR_1", Value=0)]
      VAR_1 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VAR_2", Value=1)]
      VAR_2 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VAR_3", Value=2)]
      VAR_3 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VAR_4", Value=3)]
      VAR_4 = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"WorldPoles")]
    public enum WorldPoles
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_POLES", Value=0)]
      NO_POLES = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NORTH_POLE", Value=1)]
      NORTH_POLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOUTH_POLE", Value=2)]
      SOUTH_POLE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOTH_POLES", Value=3)]
      BOTH_POLES = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"FrontType")]
    public enum FrontType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRONT_NONE", Value=0)]
      FRONT_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRONT_WARM", Value=1)]
      FRONT_WARM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRONT_COLD", Value=2)]
      FRONT_COLD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRONT_OCCLUDED", Value=3)]
      FRONT_OCCLUDED = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CumulusType")]
    public enum CumulusType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CUMULUS_NONE", Value=0)]
      CUMULUS_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CUMULUS_MEDIUM", Value=1)]
      CUMULUS_MEDIUM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CUMULUS_MULTI", Value=2)]
      CUMULUS_MULTI = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CUMULUS_NIMBUS", Value=3)]
      CUMULUS_NIMBUS = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"StratusType")]
    public enum StratusType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRATUS_NONE", Value=0)]
      STRATUS_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRATUS_ALTO", Value=1)]
      STRATUS_ALTO = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRATUS_PROPER", Value=2)]
      STRATUS_PROPER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRATUS_NIMBUS", Value=3)]
      STRATUS_NIMBUS = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"FogType")]
    public enum FogType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOG_NONE", Value=0)]
      FOG_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOG_MIST", Value=1)]
      FOG_MIST = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOG_NORMAL", Value=2)]
      FOG_NORMAL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"F0G_THICK", Value=3)]
      F0G_THICK = 3
    }
  
}