namespace MaterialStore
{
    public enum MaterialType
    {
        NONE,
        INORGANIC,
        AMBER,
        CORAL,
        GLASS_GREEN,
        GLASS_CLEAR,
        GLASS_CRYSTAL,
        WATER,
        COAL,
        POTASH,
        ASH,
        PEARLASH,
        LYE,
        MUD,
        VOMIT,
        SALT,
        FILTH_B,
        FILTH_Y,
        UNKNOWN_SUBSTANCE,
        GRIME,
        CREATURE,
        PLANT,
        DESIGNATION
    }
}
